### PR TITLE
Simplyfied build steps and instructions for Linux

### PR DESCRIPTION
**Pull request by exoji2e**

### CODE REVIEW

**Comment by flixr** [comment]
Thanks, but I would actually rather not add a script that is specific to Debian/Ubuntu...
And IMHO the steps are already trivial.

But if we should make something more clear in the README, I would be happy to update that.

**Comment by exoji2e** [comment]
So the main problem I had was that nothing showed up in `rcdiscover-GUI` once I got it to build, because of the ipv4 link-local only not being set up. 

I finally found out from reading the Quickstart Guide on paper. I think it really should be mentioned in the README under Linux. 

It's also pretty easy to set up what is needed from the command-line given an `nmcli`-installation, which is included in Ubuntu: `nmcli c a ifname eth0 type ethernet ipv4.method link-local`. That would also have been nice, since the steps in the Quickstart Guide are not consistent with Ubuntu 17/18, so setting this up from the settings-GUI looks different.

**Comment by flixr** [comment]
You should also be able to discover the rc_visard even if it has a link-local IP but your host doesn't.

Do you have reverse path filtering enabled in your system?
You can check this with
```
sysctl net.ipv4.conf.all.rp_filter
sysctl net.ipv4.conf.default.rp_filter
```
If it is enabled, you need to disable it to discover GigE Vision devices in other subnets (e.g. in link local).
```
sudo sysctl -w net.ipv4.conf.all.rp_filter=0
sudo sysctl -w net.ipv4.conf.default.rp_filter=0
sudo sysctl -w net.ipv4.conf.eth0.rp_filter=0
```

If you install the debian package, it will ask you on installation if reverse path filtering should be disabled. If yes, it installs https://github.com/roboception/rcdiscover/blob/master/debian/50-rcdiscover-rpfilter.conf

I see that this information is missing in the README, will add that.

**Comment by flixr** [comment]
Please let me know if the updated README clarifies this well enough and if disabling reverse path filtering works as expected for you: https://github.com/roboception/rcdiscover#discovering-sensors-in-other-subnets

**Pull request closed without merging**
